
export ZLIBV=1.2.13
export FRREETYPE2V=2.13.0
export JPEGV=9e
export LIBPNGV=1.6.39
export GD=gd-2.3.3
export CURLV=7.88.1
export SZIPV=2.1.1
export HDF5V=1.14.0
# I cant get 4.9.1 to build - so for now sticking with 4.8.1
#export NETCDFV=4.9.1
export NETCDFV=4.8.1
# It seems tuflow uses v4.4.5 (from Jan 2019)
export NETCDFFV=4.4.5
# however it is proving difficult to build too
#export NETCDFFV=4.6.0
