
export ZLIBV=1.3
export FRREETYPE2V=2.13.2
export JPEGV=9e
export LIBPNGV=1.6.40
export GD=gd-2.3.3
export CURLV=8.3.0
export SZIPV=2.1.1
export HDF5V=1.14.2
# I cant get 4.9.2 to build - so for now sticking with 4.8.1
#export NETCDFV=4.9.2
export NETCDFV=4.8.1
# It seems tuflow uses v4.4.5 (from Jan 2019)
#export NETCDFFV=4.4.5
# however it is proving difficult to build too
export NETCDFFV=4.6.1
